-- Baseline: the schema as it stood before migrations were introduced.
--
-- This reproduces what Hibernate's ddl-auto=update had created, so an existing
-- deployment can adopt Flyway without this file touching its data: Flyway
-- baselines a non-empty database at version 1 and starts from V2. On an empty
-- database this file runs and creates the same starting point.
--
-- Do not "correct" anything here -- fix it in a later migration instead, or
-- fresh and existing databases stop agreeing.
--
-- Portable SQL: GENERATED BY DEFAULT AS IDENTITY and TIMESTAMP(6) are standard
-- and behave the same on PostgreSQL 10+ and H2 2.x, so one set of migrations
-- serves production, development and the tests. Vendor-specific SQL would have
-- to be split per vendor and would then only ever be exercised on one of them.

CREATE TABLE groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT uq_groups_name UNIQUE (name)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    -- BCrypt hash; never the plain password.
    password VARCHAR(255) NOT NULL,
    CONSTRAINT uq_users_username UNIQUE (username)
);

CREATE TABLE user_group (
    user_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, group_id),
    CONSTRAINT fk_user_group_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_group_group FOREIGN KEY (group_id) REFERENCES groups (id)
);

CREATE TABLE files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    is_directory BOOLEAN NOT NULL,
    -- Linux-style triplet stored as a decimal integer: 755 means 755, not 0755.
    permissions INTEGER NOT NULL,
    owner_user_id BIGINT NOT NULL,
    owner_group_id BIGINT NOT NULL,
    parent_folder_id BIGINT,
    storage_key VARCHAR(255),
    custom_tags TEXT,
    description TEXT,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    -- Soft deletion timestamp.
    deleted_at TIMESTAMP(6),
    versioning_enabled BOOLEAN,
    is_locked BOOLEAN,
    locked_by_user_id BIGINT,
    locked_at TIMESTAMP(6),
    CONSTRAINT fk_files_owner_user FOREIGN KEY (owner_user_id) REFERENCES users (id),
    CONSTRAINT fk_files_owner_group FOREIGN KEY (owner_group_id) REFERENCES groups (id),
    CONSTRAINT fk_files_parent FOREIGN KEY (parent_folder_id) REFERENCES files (id),
    CONSTRAINT fk_files_locked_by FOREIGN KEY (locked_by_user_id) REFERENCES users (id)
);

CREATE TABLE file_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_entity_id BIGINT NOT NULL,
    modifier_user_id BIGINT NOT NULL,
    version INTEGER NOT NULL,
    storage_key VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_file_history_file FOREIGN KEY (file_entity_id) REFERENCES files (id),
    CONSTRAINT fk_file_history_modifier FOREIGN KEY (modifier_user_id) REFERENCES users (id)
);
